package org.activationgroup


import org.example.module.Person





rule "activationgroup-test"
    salience 1
    activation-group "activationgroup-test"
    when
        p : Person(age > 20)
    then
        System.out.println("activationgroup-test-1 执行了");
     end

rule "activationgroup-test-2"
    salience 2
    activation-group "activationgroup-test"
    when
        p : Person(age > 30)
    then
        System.out.println("activationgroup-test-2 执行了");
     end
