package org.example
import org.example.module.Person

rule "person-non"
    agenda-group "person-all-group"
    when

    then
        System.out.println("Hello world!");
end


rule "perosn-all"
    agenda-group "person-all-group"
    when
        $p : Person()
    then
        System.out.println("输出对象： " + $p);
end


rule "test001"
    agenda-group "person-all-group"
    when
       $p : Person(age > 30)
    then
        $p.setTime("40");
        update($p)
        System.out.println(" 传入了一个年龄大于30的人：" + $p);
end


rule "test0002"
    agenda-group "person-all-group"
    when
        $p : Person(name == "张三", time == 40)
    then
        System.out.println("传入了一个叫张三并且time === 40的人：" + $p);
 end
