package  org.listAndMap

import org.example.module.Person
import java.util.Map
import java.util.List

rule "list-map-test-demo"

when
    $m1 : Map()
    $m2 : Map(this["name"] == "tom")
    $m3 : Map(this["age"] >= 18)
    $l1 : List();
    $p1 : List()
then
    System.out.println("list-map-test-demo->m1:" + $m1 );
    System.out.println("list-map-test-demo->m1:" + $m2 );
    System.out.println("list-map-test-demo->m1:" + $m3 );
    System.out.println("list-map-test-demo->$l1:" + $l1 );
    System.out.println("list-map-test-demo->$l2:" + $l1 );
 end